[book]
authors = ["julei"]
language = "en"
multilingual = false
src = "src"
title = "藏经阁"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]